# Generated by Django 2.2 on 2020-03-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='position',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='surname',
        ),
    ]
