# Generated by Django 2.2 on 2020-03-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0002_auto_20200303_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='date_of_birth',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workers',
            name='position',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='surname',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
